// The story, as data. Each step: what to say, what to spotlight, what arrives, and when it is done.
// `st` is the tutorial state: { ballast: {screen, role, pub, pin, minted}, files, windows, … }. Steps with `info` wait for Next; the rest move on when done.
const have = (st, folder, re) => st.files.some((f) => f.folder === folder && re.test(f.name));
const exported = (st, re) => have(st, 'Outbox', re);
const info = (phase, title, text, extra = {}) => ({ phase, title, text, info: true, done: () => true, ...extra });

export const PHASES = ['superintendent', 'rtc', 'crew'];
export const steps = [
  // ---------- superintendent
  { phase: 'superintendent', title: 'Welcome', text: 'You are about to run a training program end to end: first as the superintendent, then as an RTC, then as crew. The desktop, the shared drive and the browser are pretend; Ballast, inside the browser, is real.\n\nThere are two ways to run Ballast. The recommended one: a saved copy, ballast.html, on the shared drive — IT put one there. Open the shared drive, go to the Ballast folder, and open ballast.html. (The Browser icon on the desktop is the other way: cror.ca/ballast.)', done: (st) => st.windows.some((w) => w.kind === 'browser') },
  info('superintendent', 'Shared drive or cror.ca?', [
    'Both open the same page. From cror.ca you always get the latest version and nothing to keep — but you depend on the site being reachable, and a website can change under you. From ballast.html on the shared drive you run a fixed file: IT can hash it once and audit it, it works with no internet, every crew member runs byte-identical code, and it will be the same file in thirty years. That is the recommended way.',
    'Getting it is the whole install: go to cror.ca/ballast, press Ctrl+S, choose "Webpage, HTML only", save it as ballast.html on the shared drive. It is one file with nothing else to fetch. (Ballast\'s top bar also has a Save a copy link that does the same.)',
    'One thing to know: a browser keeps keys per address, so the cror.ca page and the file:// page each have their own registration. Pick one and stay with it. Here in the tutorial they are the same page.',
  ].join('\n\n')),
  info('superintendent', 'The railroad metaphor', [
    'Ballast borrows its words from the CROR. The superintendent is the program director: approves tests, reads class profiles, settles appeals. The RTC (rail traffic controller) is the teacher: mints crew, issues tests, marks, files class profiles. Crew are the students. A test is issued to a class the way a clearance is issued to a train — one file, a clearance for each person, repeated back before it takes effect — and a finished attempt is a release. The marks come back as a cancellation. The RTC\'s working file is a sheet; the superintendent\'s is a book.',
    'It is admittedly a bit silly, and it may go away later. Until then, the mapping is the only thing you need to hold in your head.',
  ].join('\n\n')),
  { phase: 'superintendent', title: 'Why Ballast', text: 'Free. Simple. Serverless. Permissionless. No external dependencies. Runnable in 30 years — it should outlast some rails.\n\nOne HTML file; the browser you already have does the cryptography; the files are the network. The long form is on the desktop: open "Why Ballast.txt".', done: (st) => st.windows.some((w) => w.kind === 'notepad') },
  { phase: 'superintendent', title: 'What an armored text file is', done: (st) => st.windows.some((w) => w.kind === 'notepad' && /Armored/.test(w.title)), text: 'Ballast runs on armored text files — eight kinds, nothing else. Think of a GBO: a numbered page of plain text, transmitted by whatever means is at hand and repeated back to prove it was copied. An armored file is the same thing for a computer: a BEGIN line, readable headers, a body of letters and digits, an END line, and a sha256 as the repeat-back.\n\nThe long form, with an example, is on the desktop: open "Armored text.txt".' },
  { phase: 'superintendent', title: 'Register', text: 'Everyone starts the same way. Register with a name, a PIN (any 6 digits) and, if you like, a photo. Ballast keeps your keys in this browser.', hint: ['form.card button[type=submit]', 'Fill in name and PIN, then Register.'], done: (st) => st.ballast.pub && st.ballast.role !== undefined && st.ballast.screen && st.ballast.role === 'none' },
  { phase: 'superintendent', title: 'The first superintendent mints themself', text: 'Roles are granted by signature. Nobody is above the first superintendent, so they mint their own. Open "Nobody to mint me" and start as superintendent.', hint: ['details summary', 'Open this and click Start as superintendent.'], done: (st) => st.ballast.role === 'superintendent' },
  { phase: 'superintendent', title: 'Start your book', text: 'Your book holds the RTCs you mint, the tests you approve, and every class profile. It lives in a file under your passphrase. Start one.', hint: ['button.primary', 'Start a book.'], done: (st) => st.ballast.screen === 'book' },
  { phase: 'superintendent', title: 'Three RTCs want minting — three ways', text: 'Three instructors have registered, and their registrations reached you three different ways, because armored text goes anywhere text goes. Denise emailed hers as an attachment (Mail, on the desktop). Ray\'s attachment got blocked, so he pasted the whole block into a chat message (Messages). Tom dropped his in the shared folder, Inbox. Open all three with Ballast — the attachment, the message body with Ray\'s note still around it, and the file. Ballast finds the block wherever it is.', arrive: 'rtcRegistrations', explorer: 'Inbox', done: (st) => st.pendingSeen >= 3 },
  { phase: 'superintendent', title: 'Mint them', text: 'On the RTCs tab, mint each one. Each minted profile is a file you would send back to that instructor; here it lands in Outbox.', hint: ['.tabs button:nth-child(3)', 'The RTCs tab. Mint all three.'], done: (st) => st.files.filter((f) => f.folder === 'Outbox' && /^profile-RTC-/.test(f.name)).length >= 3 },
  { phase: 'superintendent', title: 'Tests arrive', text: 'Two test sources arrived in Tests. Open them with Ballast; they go into your inventory. Then approve them — an approval is your signature over the source, and it travels with the test when an RTC issues it. It also lets every release under that test carry a copy sealed to you.', arrive: 'testSources', explorer: 'Tests', hint: ['.tabs button:nth-child(2)', 'Test inventory: drop the sources here and approve.'], done: (st) => st.files.filter((f) => f.folder === 'Outbox' && /^approval-/.test(f.name)).length >= 2 },
  info('superintendent', 'Write one yourself', 'You can also write a test on the book. The source is plain text: a title, settings, and items separated by --- lines. Paste the example, validate it, add it. (Optional — Next when you like.)', { hint: ['textarea[placeholder^="# Title"]', 'Paste a source, Validate, Add to inventory.'] }),
  { phase: 'superintendent', title: 'Class profiles come in', text: 'The three RTCs ran Test 1 with their classes and filed class profiles: grades, strengths, weaknesses, and each RTC\'s appraisal of every crew member. Open them from Class profiles.', arrive: 'classProfiles', explorer: 'Class profiles', done: (st) => st.reportsSeen >= 3 },
  info('superintendent', 'Read the appraisals', 'On Reports, open each class profile. Compare Okafor\'s appraisals with Kowalczyk\'s and Ferland\'s. One of them rates people on their jokes and their noses. This is why the superintendent reads appraisals next to the numbers — the numbers came from a test nobody could tamper with; the words came from a person.', { hint: ['.tabs button:nth-child(1)', 'Reports: click a title to open the class profile.'] }),
  { phase: 'superintendent', title: 'An appeal', text: 'Gordon Whitfield, in Kowalczyk\'s class, says his marks do not compare: his cancellation names his release, but the grade is lower than his answers deserve. He has sent you his release file — it is in Inbox. Every release under a test you approved carries a copy sealed to you. Open it with Ballast: the book re-scores it from the approved source and compares, item by item, with what Kowalczyk reported for that release hash.', arrive: 'appeal', explorer: 'Inbox', done: (st) => !!st.appealSeen },
  info('superintendent', 'Can an RTC fail someone they dislike?', [
    'Look at Audits at the bottom of Reports: the re-score DIFFERS from what Kowalczyk reported. Two multiple-choice items he reported as wrong were right.',
    'This is what can be proven. The crew member signs the release with their own key, so the RTC cannot alter the answers. The cancellation is signed by the RTC and names the release hash, so the RTC cannot later deny what they marked. The class profile names the same hash and the per-item marks. And the audit copy lets you re-score the objective items yourself, with no help from the RTC.',
    'What cannot be proven by a machine is the mark on a short answer — that is judgement, and the remedy is the same as it always was: you read the answer. Everything else is arithmetic that anyone holding the file can repeat.',
  ].join('\n\n')),
  { phase: 'superintendent', title: 'Save the book, then step down', text: 'Save your book (any passphrase). Then you will be demoted: the real superintendent, Marguerite Boudreau, has minted your registration as an RTC. Her profile for you is in Inbox — open it with Ballast and accept the new role.', arrive: 'demoteToRtc', explorer: 'Inbox', done: (st) => st.ballast.role === 'rtc' },
  // ---------- rtc
  { phase: 'rtc', title: 'You are an RTC', text: 'Start a sheet — your desk, under a passphrase. Then make a class: Crew tab, New class, call it "Block C".', hint: ['button.primary', 'Start a sheet.'], done: (st) => st.ballast.screen === 'desk' },
  { phase: 'rtc', title: 'Registrations from crew', text: 'Four crew members registered and sent their registrations to you. Open them from Inbox, then mint each one on the Crew tab and put them in your class.', arrive: 'crewRegistrations', explorer: 'Inbox', done: (st) => st.files.filter((f) => f.folder === 'Outbox' && /^profile-crew-\d/.test(f.name)).length >= 4 },
  { phase: 'rtc', title: 'A test from the superintendent', text: 'Test 2 arrived in Tests with its approval. Open both with Ballast. On Tests, set the window — when the clearance opens and closes; outside it the file will not decrypt — choose your class and Issue. One file goes to the whole class, with a clearance for each person. It lands in Outbox.', arrive: 'testForClass', explorer: 'Tests', done: (st) => exported(st, /\.test\.txt$/) },
  { phase: 'rtc', title: 'Releases come back', text: 'Your four crew wrote the test and released. Their releases are in Releases. Open them with Ballast — one at a time here, but in real life you would select them all and drag the lot onto the desk at once, or drop one bundle file. Then on Releases click Score. Each row shows the release hash and whether the crew member\'s signature checks.', arrive: 'releases', explorer: 'Releases', done: (st) => st.releasesSeen >= 4 },
  info('rtc', 'Mark, rate, appraise', 'One item is a short answer: open review for each person and mark it. On the Crew tab, give each person a rating and write an appraisal. Write what you actually observed; the superintendent will read it beside the numbers.', { hint: ['.tabs button:nth-child(1)', 'Crew tab: rating and appraisal per person.'] }),
  { phase: 'rtc', title: 'Cancel and file the class profile', text: 'On Releases: Cancel all (export) writes every person\'s marks — signed by you, naming their release hash — into a folder you pick in a real browser, or as one file each plus one bundle of them all; here they land in Outbox. Then "Class profile to …" files the report with the superintendent — drop her profile from Inbox first if the button is missing. Save your sheet.', arrive: 'supProfile', explorer: 'Inbox', done: (st) => exported(st, /^class-profile-/) },
  { phase: 'rtc', title: 'Step down again', text: 'Denise Okafor, one of the RTCs, has minted your registration as crew. Her profile for you is in Inbox. Open it and accept.', arrive: 'demoteToCrew', explorer: 'Inbox', done: (st) => st.ballast.role === 'crew' },
  // ---------- crew
  info('crew', 'What protects the test — and what cannot', [
    'First the honest part: once a question is on your screen it is cleartext for you. No software can stop a person from reading what it shows them, remembering it, or photographing it. Ballast does not pretend otherwise, and neither should anyone selling you a "secure" test.',
    'What it does do: the test file holds every item encrypted under its own key, and only your clearance — your key plus your PIN, inside the window — opens them, one at a time. The correct answers are never in the file. Fullscreen with the keyboard locked; copy, cut, print and save refused; leaving the tab, the window or fullscreen is recorded as a break and shown to the RTC; a second tab is a break; your PIN is drawn across every item, so a photo carries your name.',
  ].join('\n\n')),
  { phase: 'crew', title: 'You are crew', text: 'Test 1 has been issued to you. It is in Inbox. Open it with Ballast, read the clearance and its window, repeat the four characters, and go fullscreen. One item at a time. Release the track when you are done.', arrive: 'testForUser', explorer: 'Inbox', done: (st) => exported(st, /^release-/) },
  info('crew', 'Your release hash', 'Ballast shows the SHA-256 of the file you just released, and keeps it on your home screen. That number is your receipt. The release is signed by your key, so nobody can change your answers; the cancellation you get back must name this hash.'),
  { phase: 'crew', title: 'Your marks', text: 'Denise scored your release and cancelled the clearance. The cancellation is in Inbox: open it to see your grade, your areas, and the rules to read.', arrive: 'cancelForUser', explorer: 'Inbox', done: (st) => ['marks', 'cancel'].includes(st.ballast.screen) },
  info('crew', 'Does it compare?', 'At the top of your marks: the release you sent, the release these marks are for, whether they compare, and who signed the marks — your RTC, the same key that minted you. Open "Marks per item" to see each mark against your answers. If the hashes ever differ, or the signature is bad, you take both files to the superintendent, who re-scores your release from its audit copy.'),
  info('crew', 'Done', 'That is the whole program: a superintendent who approves tests, reads appraisals and settles appeals; RTCs who mint crew and file class profiles; crew who write under a clearance, keep their hash, and get signed marks back. Everything that moved was a text file you could have emailed. Forget me in Ballast\'s top bar clears this pretend profile.', { done: () => false }),
];
