// The story, as data: four chunks (general, superintendent, RTC, crew), each a list of sections. A section says what to
// do, what to spotlight, what arrives, and when it is done. `st` is the tutorial state. Sections with `info` wait for
// Next; the rest move on when done.
const have = (st, folder, re) => st.files.some((f) => f.folder === folder && re.test(f.name));
const exported = (st, re) => have(st, 'Outbox', re);
const info = (phase, title, text, extra = {}) => ({ phase, title, text, info: true, done: () => true, ...extra });

export const PHASES = ['general', 'superintendent', 'rtc', 'crew'];
export const PHASE_TITLES = { general: 'Ballast', superintendent: 'Superintendent', rtc: 'RTC (teacher)', crew: 'Crew (student)' };
export const steps = [
  // ---------- general: what this is and why
  { phase: 'general', title: 'Welcome', text: 'You are about to run a training program end to end: first as the superintendent (program director), then as an RTC (teacher), then as crew (student). The desktop, the shared drive, the mail and the browser are pretend; Ballast, inside the browser, is real.\n\nBallast is a serverless HTML file. You can run it from cror.ca/ballast, or download a copy of your own (Ctrl+S, "Webpage, HTML only") and run it from a file — a shared drive, a USB stick, your desktop. The recommended way is your own copy: a fixed file IT can hash once, that needs no internet and will be the same file in thirty years. A browser keeps keys per address, so the cror.ca page and the file are two separate registrations — pick one and stay with it.\n\nOpen either one to go on: the Browser on the desktop (cror.ca), or ballast.html in the Ballast folder of the shared drive (a saved copy).', done: (st) => st.windows.some((w) => w.kind === 'browser') },
  info('general', 'Free, durable, safe, simple', [
    'Free. No licence, no seat count, no renewal, no vendor to call. Copy the file and you have another installation. Simple. One HTML file, about 190 KB of plain JavaScript a person can read end to end; three roles, eight kinds of text file, one job: issue a test, write it, mark it, prove the marks. Nothing is configured; nothing is administered.',
    'Durable. Serverless — nothing runs anywhere except in the browser in front of you: no account, no database, no service to keep up, no log on someone else\'s machine; the files are the network. Permissionless — no installer, no administrator rights, no open port, no firewall exception; it runs from a shared drive, a website or a desktop file, and the page\'s own policy forbids it from talking to the network at all. No external dependencies — no framework, no package, no CDN, no update channel; the cryptography is the browser\'s own WebCrypto, the same AES-GCM, P-256, SHA-256, HKDF and PBKDF2 that TLS uses; every file format is written down byte by byte in SPEC.md, and verify.py re-scores a release in Python with no browser at all. Runnable in thirty years — browsers do not remove JavaScript or WebCrypto; nothing expires, nothing renews, no company\'s closing takes it with it; text stays readable. Hash the file once, keep it, open it in 2056. It should outlast some rails.',
    'Safe. Every test is signed by the superintendent and checked item by item by the student\'s copy; every answer sheet is signed by the student; every mark is signed by the teacher and names the answers it marks; the superintendent can re-score any release from a copy sealed to them. What it is not: a proctoring system. Once a question is on a screen it is cleartext for the person looking at it, and no software can stop them reading, remembering or photographing it. What Ballast does instead is keep the answers out of the file, show one item at a time under fullscreen with the keyboard locked, refuse copy and print, record every break, watermark every frame with the writer\'s name, and sign everything that moves.',
    'What it does: registers people and mints their roles by signature; issues tests as one encrypted file per class with a clearance per student; takes signed releases back; scores, marks, rates and appraises; files class profiles with the superintendent; settles appeals; and carries the public CROR 2025 as a rulebook you can search, annotate and open during open-book tests.',
  ].join('\n\n')),
  info('general', 'The railroad metaphor', [
    'Ballast borrows its words from the CROR. The superintendent is the program director: approves tests, reads class profiles, settles appeals. The RTC (rail traffic controller) is the teacher: mints crew, issues tests, marks, files class profiles. Crew are the students. A test is issued to a class the way a clearance is issued to a train — one file, a clearance for each person, repeated back before it takes effect — and a finished attempt is a release. The marks come back as a cancellation. The RTC\'s working file is a sheet; the superintendent\'s is a book.',
    'It is admittedly a bit silly, and it may go away later. Until then, the mapping is the only thing you need to hold in your head.',
  ].join('\n\n')),
  { phase: 'general', title: 'Armored text files', arrive: 'armorExample', explorer: 'Ballast', done: (st) => st.windows.some((w) => w.kind === 'notepad' && /example-armored/.test(w.title)), text: [
    'Everything Ballast sends or receives is an armored text file — eight kinds: PROFILE, TEST, RELEASE, CANCEL, APPROVAL, REPORT, SHEET, BOOK. There is nothing else. The idea is older than the web: PGP has wrapped keys and messages this way since 1991, so that they could travel through mail systems that mangled anything but letters.',
    'It is the GBO of Ballast. A General Bulletin Order is a page of plain text: numbered, addressed, transmitted by whatever means is at hand — read over the radio, printed at the terminal, handed across a desk — and repeated back to prove it was copied. The medium never matters; the words do. An armored file is the same thing for a computer, and it carries its own repeat-back.',
    'IT left one on the shared drive: open example-armored-file.txt in the Ballast folder (it opens in Notepad).',
  ].join('\n\n') },
  info('general', 'What is in the file', [
    'Top to bottom: a BEGIN line naming the kind; a few readable headers — version, role, name, PIN, and a sha256; a blank line; the body, only letters, digits, + / and =; an END line. The headers are for people and for IT: anyone can see what the file is, who it is for and whether it arrived intact, without opening it. The sha256 is the repeat-back: the receiver recomputes it and refuses a mangled file. The body is the file proper — JSON, signed, and encrypted where it must be — written as base64 so nothing between sender and receiver can damage it.',
    'Why it is good: it goes anywhere text goes — an attachment, an email body, a chat message, a shared folder, a USB stick, a printout — and Ballast finds the block inside whatever surrounds it. It survives everything that breaks binary files: mail gateways, line endings, copy and paste, smart quotes. It is inert: a text file cannot run, and Ballast never executes what it reads. It is auditable with any text editor. And it is durable: text is the one format that will still open in 2056.',
    'What the envelope does not do: keep secrets. The body does that. A TEST holds every item encrypted under its own key; a RELEASE is sealed to one RTC and signed by one crew member; a CANCEL is sealed to one crew member and signed by the RTC. Copy an armored file to a hundred people and only the ones it was sealed to can open it — and the sha256 tells everyone else it was not touched.',
  ].join('\n\n')),
  info('general', 'How signing keeps everyone honest', [
    'Tests. The superintendent signs a test: the signature covers the source and a hash of every item the student will see. The test file carries that approval. When a student is minted, their profile carries the superintendent\'s public key — proven, because it also carries their teacher\'s own mint by that superintendent. So the student\'s copy refuses a test with no approval or one approved by anyone else, and checks each item against the approval as it opens. A teacher cannot edit, add or swap a question.',
    'Answers. The student\'s release is signed with the student\'s own key and sealed to the teacher, with a second copy sealed to the superintendent. The teacher cannot alter an answer. The marks come back signed by the teacher and naming the release hash, item by item; the class profile names the same hashes. If a student doubts a mark, the superintendent re-scores the release from the audit copy without the teacher\'s help.',
    'Nothing here needs a server or an account: the keys live in each person\'s browser, and the proofs travel inside the files.',
  ].join('\n\n')),
  // ---------- superintendent
  { phase: 'superintendent', title: 'Register', text: 'Everyone starts the same way. Register with a name, a PIN (any 6 digits) and, if you like, a photo. Ballast keeps your keys in this browser.', hint: ['form.card button[type=submit]', 'Fill in name and PIN, then Register.'], done: (st) => st.ballast.pub && st.ballast.role !== undefined && st.ballast.screen && st.ballast.role === 'none' },
  { phase: 'superintendent', title: 'Mint yourself', text: 'Roles are granted by signature. Nobody is above the first superintendent, so they mint their own. Open "Nobody to mint me" and start as superintendent.', hint: ['details summary', 'Open this and click Start as superintendent.'], done: (st) => st.ballast.role === 'superintendent' },
  { phase: 'superintendent', title: 'Start your book', text: 'Your book holds the RTCs you mint, the tests you approve, and every class profile. It lives in a file under your passphrase. Start one.', hint: ['button.primary', 'Start a book.'], done: (st) => st.ballast.screen === 'book' },
  { phase: 'superintendent', title: 'Mint teachers — three ways in', text: 'Three instructors have registered, and their registrations reached you three different ways, because armored text goes anywhere text goes. Denise emailed hers as an attachment (Mail, on the desktop). Ray\'s attachment got blocked, so he pasted the whole block into a chat message (Messages). Tom dropped his in the shared folder, Inbox. Open all three with Ballast — the attachment, the message body with Ray\'s note still around it, and the file. Ballast finds the block wherever it is.', arrive: 'rtcRegistrations', explorer: 'Inbox', done: (st) => st.pendingSeen >= 3 },
  { phase: 'superintendent', title: 'Mint them', text: 'On the RTCs tab, mint each one. Each minted profile is a file you would send back to that instructor; here it lands in Outbox. From now on those three, and everyone they mint, carry your key as the superintendent they trust.', hint: ['.tabs button:nth-child(3)', 'The RTCs tab. Mint all three.'], done: (st) => st.files.filter((f) => f.folder === 'Outbox' && /^profile-RTC-/.test(f.name)).length >= 3 },
  { phase: 'superintendent', title: 'Make a test — in Notepad', text: 'A test is a plain text file: a title and settings, then items separated by --- lines. You can write one anywhere that writes text. Open Notepad on the desktop: it holds a small test to start from. Change a question if you like, then Save as… into the Tests folder of the shared drive, and open the saved file with Ballast — it lands in your inventory.', arrive: null, done: (st) => !!st.authored },
  info('superintendent', 'Make a test — in Ballast', 'Ballast has an editor of its own on the Test inventory tab: Write a test, with buttons that add a multiple-choice, matching or short-answer item, Validate to check the format, Add to inventory. With the rulebook loaded, Link refs to rulebook ties every item to the exact wording it was written against, and Check tells you later which items a new CROR edition touched.', { hint: ['textarea[placeholder^="# Title"]', 'The editor. Try the + buttons and Validate.'] }),
  { phase: 'superintendent', title: 'Sign tests', text: 'Two more test sources arrived in Tests. Open them with Ballast; they go into your inventory. Then approve them — including the one you wrote. An approval is your signature over the source and over every item; it travels with the test when an RTC issues it, and a student\'s copy will not open a test without it. It also lets every release under that test carry a copy sealed to you.', arrive: 'testSources', explorer: 'Tests', hint: ['.tabs button:nth-child(2)', 'Test inventory: drop the sources here and approve.'], done: (st) => st.files.filter((f) => f.folder === 'Outbox' && /^approval-/.test(f.name)).length >= 2 },
  { phase: 'superintendent', title: 'Class profiles come in', text: 'The three RTCs ran Test 1 with their classes and filed class profiles: grades, strengths, weaknesses, and each RTC\'s appraisal of every crew member. Open them from Class profiles.', arrive: 'classProfiles', explorer: 'Class profiles', done: (st) => st.reportsSeen >= 3 },
  info('superintendent', 'Read the appraisals', 'On Reports, open each class profile. Compare Okafor\'s appraisals with Kowalczyk\'s and Ferland\'s. One of them rates people on their jokes and their noses. This is why the superintendent reads appraisals next to the numbers — the numbers came from a test nobody could tamper with; the words came from a person.', { hint: ['.tabs button:nth-child(1)', 'Reports: click a title to open the class profile.'] }),
  { phase: 'superintendent', title: 'An appeal', text: 'Gordon Whitfield, in Kowalczyk\'s class, says his marks do not compare: his cancellation names his release, but the grade is lower than his answers deserve. He has sent you his release file — it is in Inbox. Every release under a test you approved carries a copy sealed to you. Open it with Ballast: the book re-scores it from the approved source and compares, item by item, with what Kowalczyk reported for that release hash.', arrive: 'appeal', explorer: 'Inbox', done: (st) => !!st.appealSeen },
  info('superintendent', 'Can a teacher fail someone they dislike?', [
    'Look at Audits at the bottom of Reports: the re-score DIFFERS from what Kowalczyk reported. Two multiple-choice items he reported as wrong were right.',
    'This is what can be proven. The crew member signs the release with their own key, so the RTC cannot alter the answers. The cancellation is signed by the RTC and names the release hash, so the RTC cannot later deny what they marked. The class profile names the same hash and the per-item marks. And the audit copy lets you re-score the objective items yourself, with no help from the RTC.',
    'What cannot be proven by a machine is the mark on a short answer — that is judgement, and the remedy is the same as it always was: you read the answer. Everything else is arithmetic that anyone holding the file can repeat.',
  ].join('\n\n')),
  { phase: 'superintendent', title: 'Save the book, then step down', text: 'Save your book (any passphrase). Then you will be demoted: the real superintendent, Marguerite Boudreau, has minted your registration as an RTC. Her profile for you is in Inbox — open it with Ballast and accept the new role.', arrive: 'demoteToRtc', explorer: 'Inbox', done: (st) => st.ballast.role === 'rtc' },
  // ---------- rtc
  { phase: 'rtc', title: 'Start a sheet', text: 'Your desk is a sheet, under a passphrase. Start one. Then make a class: Crew tab, New class, call it "Block C".', hint: ['button.primary', 'Start a sheet.'], done: (st) => st.ballast.screen === 'desk' },
  { phase: 'rtc', title: 'Mint students', text: 'Four crew members registered and sent their registrations to you. Open them from Inbox, then mint each one on the Crew tab and put them in your class. Their minted profiles carry your superintendent\'s key, so they will only ever write tests she signed.', arrive: 'crewRegistrations', explorer: 'Inbox', done: (st) => st.files.filter((f) => f.folder === 'Outbox' && /^profile-crew-\d/.test(f.name)).length >= 4 },
  { phase: 'rtc', title: 'Disseminate a test', text: 'Test 2 arrived in Tests with the superintendent\'s approval. Open both with Ballast. On Tests, set the window — when the clearance opens and closes; outside it the file will not decrypt — choose your class and Issue. One file goes to the whole class, with a clearance for each person. It lands in Outbox. Without the approval, Ballast warns you: crew would refuse it.', arrive: 'testForClass', explorer: 'Tests', done: (st) => exported(st, /\.test\.txt$/) },
  { phase: 'rtc', title: 'Receive returns', text: 'Your four crew wrote the test and released. Their releases are in Releases. Open them with Ballast — one at a time here, but in real life you would select them all and drag the lot onto the desk at once, or drop one bundle file. Then on Releases click Score. Each row shows the release hash and whether the crew member\'s signature checks.', arrive: 'releases', explorer: 'Releases', done: (st) => st.releasesSeen >= 4 },
  info('rtc', 'Mark, rate, appraise', 'One item is a short answer: open review for each person and mark it. On the Crew tab, give each person a rating and write an appraisal. Write what you actually observed; the superintendent will read it beside the numbers.', { hint: ['.tabs button:nth-child(1)', 'Crew tab: rating and appraisal per person.'] }),
  { phase: 'rtc', title: 'Pass out grades', text: 'On Releases: Cancel all (export) writes every person\'s marks — signed by you, naming their release hash — into a folder you pick in a real browser, or as one file each plus one bundle of them all; here they land in Outbox. Then "Class profile to …" files the report with the superintendent — drop her profile from Inbox first if the button is missing. Save your sheet.', arrive: 'supProfile', explorer: 'Inbox', done: (st) => exported(st, /^class-profile-/) },
  { phase: 'rtc', title: 'Step down again', text: 'Denise Okafor, one of the RTCs, has minted your registration as crew. Her profile for you is in Inbox. Open it and accept. Look at your profile card afterwards: "under superintendent Marguerite Boudreau" — that is the key your copy will check tests against.', arrive: 'demoteToCrew', explorer: 'Inbox', done: (st) => st.ballast.role === 'crew' },
  // ---------- crew
  info('crew', 'What protects the test — and what cannot', [
    'First the honest part: once a question is on your screen it is cleartext for you. No software can stop a person from reading what it shows them, remembering it, or photographing it. Ballast does not pretend otherwise, and neither should anyone selling you a "secure" test.',
    'What it does do: the test file holds every item encrypted under its own key, and only your clearance — your key plus your PIN, inside the window — opens them, one at a time. The correct answers are never in the file. Fullscreen with the keyboard locked; copy, cut, print and save refused; leaving the tab, the window or fullscreen is recorded as a break and shown to the RTC; a second tab is a break; your PIN is drawn across every item, so a photo carries your name.',
  ].join('\n\n')),
  { phase: 'crew', title: 'Do a test', text: 'Test 1 has been issued to you. It is in Inbox. Open it with Ballast: your copy checks the superintendent\'s approval against the key in your own profile before it shows you anything. Read the clearance and its window, repeat the four characters, and go fullscreen. One item at a time — each one is checked against the approval as it opens. Release the track when you are done.', arrive: 'testForUser', explorer: 'Inbox', done: (st) => exported(st, /^release-/) },
  info('crew', 'Your release hash', 'Ballast shows the SHA-256 of the file you just released, and keeps it on your home screen. That number is your receipt. The release is signed by your key, so nobody can change your answers; the cancellation you get back must name this hash.'),
  { phase: 'crew', title: 'Receive feedback', text: 'Denise scored your release and cancelled the clearance. The cancellation is in Inbox: open it to see your grade, your areas, and the rules to read.', arrive: 'cancelForUser', explorer: 'Inbox', done: (st) => ['marks', 'cancel'].includes(st.ballast.screen) },
  info('crew', 'Does it compare?', 'At the top of your marks: the release you sent, the release these marks are for, whether they compare, and who signed the marks — your RTC, the same key that minted you. Open "Marks per item" to see each mark against your answers. If the hashes ever differ, or the signature is bad, you take both files to the superintendent, who re-scores your release from its audit copy.'),
  info('crew', 'Exercises and the rulebook', 'Your home screen also has Exercises — signals and definitions, open book, every question tied to the public CROR 2025 — and the top bar has the Rulebook: load cror-2025.json once (from the Reader page, Document out) and it is there to search and annotate, and to open beside an open-book test.'),
  info('crew', 'Done', 'That is the whole program: a superintendent who signs tests, reads appraisals and settles appeals; RTCs who mint crew and file class profiles; crew who write under a clearance, keep their hash, and get signed marks back. Everything that moved was a text file you could have emailed. Forget me in Ballast\'s top bar clears this pretend profile.', { done: () => false }),
];
