// Built-in exercises: generated by exercises/make.mjs from public sources, checked by exercises/check.mjs at build.
import signals from './signals.txt';
import definitions from './definitions.txt';
export const exercises = [
  { name: 'Signals — aspects and indications', about: 'Read the aspect, name the indication; name the indication, say what it requires. Rules 405–439.', source: signals },
  { name: 'Definitions', about: 'Match the CROR definition to its term.', source: definitions },
];
